// LeetCode 389.Find the Difference

//Question: You are given two strings s and t.
// String t is generated by random shuffling string s and then add one more letter at a random position.
// Return the letter that was added to t.

//Solution: contains the helper function
class Solution
{
	public:
    char findTheDifference(string s, string t)
	  {
        int difference,i;
        difference=0;
        for(i=0;i<s.size();i++)
		    {
            difference -= s[i];
            difference += t[i];
        } 
        difference += t[t.size()-1];
        return (char)difference;
    }
};
